"""Add employee table

Revision ID: 1f420c329f74
Revises: 
Create Date: 2025-04-01 11:08:44.612276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f420c329f74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'gender',
               existing_type=mysql.ENUM('Male', 'Female', 'Other'),
               type_=sa.String(length=10),
               nullable=True)
    op.alter_column('employees', 'department',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employees', 'job_title',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employees', 'mentor_role',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('employees', 'skills',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('employees', 'interests',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('employees', 'location',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'education',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'project_involvement',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'employee_status',
               existing_type=mysql.ENUM('Active', 'Inactive', 'On Leave', 'Terminated'),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'Active'"))
    op.alter_column('employees', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('employees', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
    op.alter_column('employees', 'date_of_joining',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'performance_score',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('employees', 'preferred_work_style',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'languages_spoken',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('employees', 'linkedin_profile',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index('email', table_name='employees')
    op.drop_index('phone_number', table_name='employees')
    op.drop_column('employees', 'created_at')
    op.drop_column('employees', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('employees', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.create_index('phone_number', 'employees', ['phone_number'], unique=True)
    op.create_index('email', 'employees', ['email'], unique=True)
    op.alter_column('employees', 'linkedin_profile',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'languages_spoken',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'preferred_work_style',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'performance_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('employees', 'date_of_joining',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'phone_number',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('employees', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('employees', 'employee_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Active', 'Inactive', 'On Leave', 'Terminated'),
               nullable=False,
               existing_server_default=sa.text("'Active'"))
    op.alter_column('employees', 'project_involvement',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'education',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'interests',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'skills',
               existing_type=sa.String(length=200),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('employees', 'mentor_role',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'job_title',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'department',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('employees', 'gender',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('Male', 'Female', 'Other'),
               nullable=False)
    op.alter_column('employees', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
